name: Blog posts on ReadMe
on:
  workflow_dispatch:
  schedule:
    # Runs every day at 9am UTC
    - cron: '0 4 * * *'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: sarisia/actions-readme-feed@v1
        with:
          url: https://www.marcveens.nl/feed.xml
          file: 'README.md'
          format: - [${title}](${url}) - ${year}-${02month}-${02day}
      - name: Commit file changes
        run: |
            git config --global user.email "actions@users.noreply.github.com"
            git config --global user.name "README-bot"
            git add .
            git diff --quiet --cached || git commit -m "Update README" 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}